#include <stdio.h>
#include <stdlib.h>
#include "cjson.h"
#include <locale.h>
#include "cjson.h"

int main(){

const char* big_json =
"{"
    "\"repository\":{"
        "\"id\":1296269,"
        "\"name\":\"JsonParse\","
        "\"full_name\":\"suixinz/JsonParse\","
        "\"private\":false,"
        "\"owner\":{"
            "\"id\":1,"
            "\"login\":\"suixinz\","
            "\"avatar_url\":\"https://avatars.githubusercontent.com/u/1?v=4\","
            "\"type\":\"User\","
            "\"site_admin\":false,"
            "\"created_at\":\"2024-01-15T12:00:00Z\","
            "\"permissions\":{\"admin\":true,\"push\":true,\"pull\":true}"
        "},"
        "\"description\":\"A lightweight JSON parser with arena allocator\","
        "\"fork\":false,"
        "\"created_at\":\"2024-01-15T12:00:00Z\","
        "\"updated_at\":\"2026-08-20T03:30:00Z\","
        "\"pushed_at\":\"2026-08-20T03:30:00Z\","
        "\"size\":1024,"
        "\"stargazers_count\":128,"
        "\"watchers_count\":128,"
        "\"forks_count\":16,"
        "\"open_issues_count\":3,"
        "\"language\":\"C\","
        "\"license\":{"
            "\"key\":\"mit\","
            "\"name\":\"MIT License\","
            "\"spdx_id\":\"MIT\","
            "\"url\":\"https://api.github.com/licenses/mit\""
        "},"
        "\"topics\":[\"json\",\"parser\",\"c\",\"arena-allocator\",\"interview\"],"
        "\"has_issues\":true,"
        "\"has_projects\":false,"
        "\"has_wiki\":true,"
        "\"archived\":false,"
        "\"disabled\":false,"
        "\"visibility\":\"public\","
        "\"default_branch\":\"main\","
        "\"temp_clone_token\":null,"
        "\"network_count\":16,"
        "\"subscribers_count\":8"
    "},"
    "\"commits\":["
        "{"
            "\"sha\":\"abc123def456\","
            "\"node_id\":\"MDY6Q29tbWl0MTI5NjI2OTo=\","
            "\"commit\":{"
                "\"author\":{\"name\":\"suixinz\",\"email\":\"suixin@example.com\",\"date\":\"2026-08-20T03:00:00Z\"},"
                "\"committer\":{\"name\":\"suixinz\",\"email\":\"suixin@example.com\",\"date\":\"2026-08-20T03:00:00Z\"},"
                "\"message\":\"Implement stringify with two-pass approach\","
                "\"tree\":{\"sha\":\"def789\",\"url\":\"https://api.github.com/repos/suixinz/JsonParse/git/trees/def789\"}"
            "},"
            "\"url\":\"https://api.github.com/repos/suixinz/JsonParse/commits/abc123\","
            "\"html_url\":\"https://github.com/suixinz/JsonParse/commit/abc123\","
            "\"comments_url\":\"https://api.github.com/repos/suixinz/JsonParse/commits/abc123/comments\","
            "\"author\":{\"id\":1,\"login\":\"suixinz\",\"avatar_url\":\"https://avatars.githubusercontent.com/u/1?v=4\"},"
            "\"committer\":{\"id\":1,\"login\":\"suixinz\",\"avatar_url\":\"https://avatars.githubusercontent.com/u/1?v=4\"},"
            "\"parents\":[{\"sha\":\"old456\",\"url\":\"https://api.github.com/repos/suixinz/JsonParse/commits/old456\"}],"
            "\"stats\":{\"total\":42,\"additions\":35,\"deletions\":7},"
            "\"files\":["
                "{\"filename\":\"src/cjson.c\",\"status\":\"modified\",\"additions\":20,\"deletions\":5,\"changes\":25},"
                "{\"filename\":\"src/cjson.h\",\"status\":\"modified\",\"additions\":10,\"deletions\":2,\"changes\":12},"
                "{\"filename\":\"tests/main.c\",\"status\":\"added\",\"additions\":5,\"deletions\":0,\"changes\":5}"
            "]"
        "},"
        "{"
            "\"sha\":\"def456ghi789\","
            "\"node_id\":\"MDY6Q29tbWl0MTI5NjI2OTo=\","
            "\"commit\":{"
                "\"author\":{\"name\":\"suixinz\",\"email\":\"suixin@example.com\",\"date\":\"2026-08-19T14:00:00Z\"},"
                "\"committer\":{\"name\":\"suixinz\",\"email\":\"suixin@example.com\",\"date\":\"2026-08-19T14:00:00Z\"},"
                "\"message\":\"Add arena allocator and error code system\","
                "\"tree\":{\"sha\":\"abc123\",\"url\":\"https://api.github.com/repos/suixinz/JsonParse/git/trees/abc123\"}"
            "},"
            "\"url\":\"https://api.github.com/repos/suixinz/JsonParse/commits/def456\","
            "\"html_url\":\"https://github.com/suixinz/JsonParse/commit/def456\","
            "\"author\":{\"id\":1,\"login\":\"suixinz\",\"avatar_url\":\"https://avatars.githubusercontent.com/u/1?v=4\"},"
            "\"committer\":{\"id\":1,\"login\":\"suixinz\",\"avatar_url\":\"https://avatars.githubusercontent.com/u/1?v=4\"},"
            "\"parents\":[{\"sha\":\"first123\",\"url\":\"https://api.github.com/repos/suixinz/JsonParse/commits/first123\"}],"
            "\"stats\":{\"total\":120,\"additions\":100,\"deletions\":20},"
            "\"files\":["
                "{\"filename\":\"src/arena.c\",\"status\":\"added\",\"additions\":80,\"deletions\":0,\"changes\":80},"
                "{\"filename\":\"src/arena.h\",\"status\":\"added\",\"additions\":20,\"deletions\":0,\"changes\":20}"
            "]"
        "}"
    "],"
    "\"pull_requests\":["
        "{"
            "\"id\":1,"
            "\"number\":1,"
            "\"state\":\"open\","
            "\"title\":\"Add UTF-8 surrogate pair support\","
            "\"user\":{\"id\":2,\"login\":\"contributor\",\"avatar_url\":\"https://avatars.githubusercontent.com/u/2?v=4\"},"
            "\"body\":\"This PR adds support for parsing surrogate pairs.\","
            "\"labels\":[{\"id\":1,\"name\":\"enhancement\",\"color\":\"a2eeef\"}],"
            "\"assignees\":[{\"id\":1,\"login\":\"suixinz\"}],"
            "\"milestone\":null,"
            "\"created_at\":\"2026-08-18T10:00:00Z\","
            "\"updated_at\":\"2026-08-19T08:00:00Z\","
            "\"closed_at\":null,"
            "\"merged_at\":null"
        "}"
    "],"
    "\"issues\":{"
        "\"total_count\":3,"
        "\"items\":["
            "{\"id\":1,\"number\":1,\"title\":\"Support stringify\",\"state\":\"closed\",\"user\":{\"id\":1,\"login\":\"suixinz\"}},"
            "{\"id\":2,\"number\":2,\"title\":\"Add error handling\",\"state\":\"closed\",\"user\":{\"id\":1,\"login\":\"suixinz\"}},"
            "{\"id\":3,\"number\":3,\"title\":\"Benchmark against simdjson\",\"state\":\"open\",\"user\":{\"id\":1,\"login\":\"suixinz\"}}"
        "]"
    "},"
    "\"rate_limit\":{"
        "\"limit\":5000,"
        "\"remaining\":4997,"
        "\"reset\":1700003600,"
        "\"used\":3,"
        "\"resource\":\"core\""
    "}"
"}";


    cjson_t* root = NULL;

    arena* arena_pool = arena_create();

    if(arena_pool == NULL){
        return 0;
    }

    cjson_parse(big_json, arena_pool, &root);

    cjson_display(root);

    return 0;

}